[Settings]
  ID = "cec7b5b3-e10c-4834-8677-ea1ff52aec2b"

[build]
  command = "npm run build && npm run generate"
  publish = "dist"

[context.production]
  environment = { NODE_ENV = "8.7.0", REPOSITORY_URL = "https://github.com/davidroyer/nuxt-bulma" }
